/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingScenariosRouteImport } from './routes/_marketing.scenarios'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as MarketingIntegrationsRouteImport } from './routes/_marketing.integrations'
import { Route as MarketingFirst100RouteImport } from './routes/_marketing.first-100'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing.features'
import { Route as MarketingFaqRouteImport } from './routes/_marketing.faq'
import { Route as MarketingContactsRouteImport } from './routes/_marketing.contacts'
import { Route as MarketingCasesRouteImport } from './routes/_marketing.cases'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthCallbackRouteImport } from './routes/_auth.callback'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppAssistantsRouteImport } from './routes/_app.assistants'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as MarketingScenariosNicheRouteImport } from './routes/_marketing.scenarios.$niche'
import { Route as MarketingLegalPrivacyRouteImport } from './routes/_marketing.legal.privacy'
import { Route as MarketingLegalOfferRouteImport } from './routes/_marketing.legal.offer'
import { Route as MarketingCasesSlugRouteImport } from './routes/_marketing.cases.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingScenariosRoute = MarketingScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingIntegrationsRoute = MarketingIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFirst100Route = MarketingFirst100RouteImport.update({
  id: '/first-100',
  path: '/first-100',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactsRoute = MarketingContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCasesRoute = MarketingCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantsRoute = AppAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const MarketingScenariosNicheRoute = MarketingScenariosNicheRouteImport.update({
  id: '/$niche',
  path: '/$niche',
  getParentRoute: () => MarketingScenariosRoute,
} as any)
const MarketingLegalPrivacyRoute = MarketingLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalOfferRoute = MarketingLegalOfferRouteImport.update({
  id: '/legal/offer',
  path: '/legal/offer',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCasesSlugRoute = MarketingCasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/app': typeof AppAppRoute
  '/assistants': typeof AppAssistantsRoute
  '/leads': typeof AppLeadsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/about': typeof MarketingAboutRoute
  '/cases': typeof MarketingCasesRouteWithChildren
  '/contacts': typeof MarketingContactsRoute
  '/faq': typeof MarketingFaqRoute
  '/features': typeof MarketingFeaturesRoute
  '/first-100': typeof MarketingFirst100Route
  '/integrations': typeof MarketingIntegrationsRoute
  '/pricing': typeof MarketingPricingRoute
  '/scenarios': typeof MarketingScenariosRouteWithChildren
  '/cases/$slug': typeof MarketingCasesSlugRoute
  '/legal/offer': typeof MarketingLegalOfferRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/scenarios/$niche': typeof MarketingScenariosNicheRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/app': typeof AppAppRoute
  '/assistants': typeof AppAssistantsRoute
  '/leads': typeof AppLeadsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/about': typeof MarketingAboutRoute
  '/cases': typeof MarketingCasesRouteWithChildren
  '/contacts': typeof MarketingContactsRoute
  '/faq': typeof MarketingFaqRoute
  '/features': typeof MarketingFeaturesRoute
  '/first-100': typeof MarketingFirst100Route
  '/integrations': typeof MarketingIntegrationsRoute
  '/pricing': typeof MarketingPricingRoute
  '/scenarios': typeof MarketingScenariosRouteWithChildren
  '/cases/$slug': typeof MarketingCasesSlugRoute
  '/legal/offer': typeof MarketingLegalOfferRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/scenarios/$niche': typeof MarketingScenariosNicheRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/app': typeof AppAppRoute
  '/_app/assistants': typeof AppAssistantsRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/cases': typeof MarketingCasesRouteWithChildren
  '/_marketing/contacts': typeof MarketingContactsRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/first-100': typeof MarketingFirst100Route
  '/_marketing/integrations': typeof MarketingIntegrationsRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/scenarios': typeof MarketingScenariosRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/cases/$slug': typeof MarketingCasesSlugRoute
  '/_marketing/legal/offer': typeof MarketingLegalOfferRoute
  '/_marketing/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/_marketing/scenarios/$niche': typeof MarketingScenariosNicheRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/analytics'
    | '/app'
    | '/assistants'
    | '/leads'
    | '/settings'
    | '/team'
    | '/callback'
    | '/login'
    | '/signup'
    | '/about'
    | '/cases'
    | '/contacts'
    | '/faq'
    | '/features'
    | '/first-100'
    | '/integrations'
    | '/pricing'
    | '/scenarios'
    | '/cases/$slug'
    | '/legal/offer'
    | '/legal/privacy'
    | '/scenarios/$niche'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/analytics'
    | '/app'
    | '/assistants'
    | '/leads'
    | '/settings'
    | '/team'
    | '/callback'
    | '/login'
    | '/signup'
    | '/about'
    | '/cases'
    | '/contacts'
    | '/faq'
    | '/features'
    | '/first-100'
    | '/integrations'
    | '/pricing'
    | '/scenarios'
    | '/cases/$slug'
    | '/legal/offer'
    | '/legal/privacy'
    | '/scenarios/$niche'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_marketing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_app/analytics'
    | '/_app/app'
    | '/_app/assistants'
    | '/_app/leads'
    | '/_app/settings'
    | '/_app/team'
    | '/_auth/callback'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_marketing/about'
    | '/_marketing/cases'
    | '/_marketing/contacts'
    | '/_marketing/faq'
    | '/_marketing/features'
    | '/_marketing/first-100'
    | '/_marketing/integrations'
    | '/_marketing/pricing'
    | '/_marketing/scenarios'
    | '/_marketing/'
    | '/_marketing/cases/$slug'
    | '/_marketing/legal/offer'
    | '/_marketing/legal/privacy'
    | '/_marketing/scenarios/$niche'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/scenarios': {
      id: '/_marketing/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof MarketingScenariosRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/integrations': {
      id: '/_marketing/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof MarketingIntegrationsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/first-100': {
      id: '/_marketing/first-100'
      path: '/first-100'
      fullPath: '/first-100'
      preLoaderRoute: typeof MarketingFirst100RouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contacts': {
      id: '/_marketing/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof MarketingContactsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/cases': {
      id: '/_marketing/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof MarketingCasesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistants': {
      id: '/_app/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AppAssistantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/scenarios/$niche': {
      id: '/_marketing/scenarios/$niche'
      path: '/$niche'
      fullPath: '/scenarios/$niche'
      preLoaderRoute: typeof MarketingScenariosNicheRouteImport
      parentRoute: typeof MarketingScenariosRoute
    }
    '/_marketing/legal/privacy': {
      id: '/_marketing/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof MarketingLegalPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/offer': {
      id: '/_marketing/legal/offer'
      path: '/legal/offer'
      fullPath: '/legal/offer'
      preLoaderRoute: typeof MarketingLegalOfferRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/cases/$slug': {
      id: '/_marketing/cases/$slug'
      path: '/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof MarketingCasesSlugRouteImport
      parentRoute: typeof MarketingCasesRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppRoute: typeof AppAppRoute
  AppAssistantsRoute: typeof AppAssistantsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppRoute: AppAppRoute,
  AppAssistantsRoute: AppAssistantsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingCasesRouteChildren {
  MarketingCasesSlugRoute: typeof MarketingCasesSlugRoute
}

const MarketingCasesRouteChildren: MarketingCasesRouteChildren = {
  MarketingCasesSlugRoute: MarketingCasesSlugRoute,
}

const MarketingCasesRouteWithChildren = MarketingCasesRoute._addFileChildren(
  MarketingCasesRouteChildren,
)

interface MarketingScenariosRouteChildren {
  MarketingScenariosNicheRoute: typeof MarketingScenariosNicheRoute
}

const MarketingScenariosRouteChildren: MarketingScenariosRouteChildren = {
  MarketingScenariosNicheRoute: MarketingScenariosNicheRoute,
}

const MarketingScenariosRouteWithChildren =
  MarketingScenariosRoute._addFileChildren(MarketingScenariosRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingCasesRoute: typeof MarketingCasesRouteWithChildren
  MarketingContactsRoute: typeof MarketingContactsRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingFirst100Route: typeof MarketingFirst100Route
  MarketingIntegrationsRoute: typeof MarketingIntegrationsRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingScenariosRoute: typeof MarketingScenariosRouteWithChildren
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingLegalOfferRoute: typeof MarketingLegalOfferRoute
  MarketingLegalPrivacyRoute: typeof MarketingLegalPrivacyRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingCasesRoute: MarketingCasesRouteWithChildren,
  MarketingContactsRoute: MarketingContactsRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingFirst100Route: MarketingFirst100Route,
  MarketingIntegrationsRoute: MarketingIntegrationsRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingScenariosRoute: MarketingScenariosRouteWithChildren,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingLegalOfferRoute: MarketingLegalOfferRoute,
  MarketingLegalPrivacyRoute: MarketingLegalPrivacyRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
